[2025-09-24T09:24:29.358+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sales_dag.final_merge.merge_data_to_mainTable scheduled__2025-09-23T00:00:00+00:00 [queued]>
[2025-09-24T09:24:29.371+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sales_dag.final_merge.merge_data_to_mainTable scheduled__2025-09-23T00:00:00+00:00 [queued]>
[2025-09-24T09:24:29.372+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2025-09-24T09:24:29.395+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): final_merge.merge_data_to_mainTable> on 2025-09-23 00:00:00+00:00
[2025-09-24T09:24:29.404+0000] {standard_task_runner.py:57} INFO - Started process 193 to run task
[2025-09-24T09:24:29.408+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'sales_dag', 'final_merge.merge_data_to_mainTable', 'scheduled__2025-09-23T00:00:00+00:00', '--job-id', '234', '--raw', '--subdir', 'DAGS_FOLDER/sales_dag.py', '--cfg-path', '/tmp/tmpl66rug1m']
[2025-09-24T09:24:29.412+0000] {standard_task_runner.py:85} INFO - Job 234: Subtask final_merge.merge_data_to_mainTable
[2025-09-24T09:24:29.455+0000] {logging_mixin.py:151} WARNING - /home/airflow/.local/lib/python3.8/site-packages/airflow/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-09-24T09:24:29.579+0000] {task_command.py:415} INFO - Running <TaskInstance: sales_dag.final_merge.merge_data_to_mainTable scheduled__2025-09-23T00:00:00+00:00 [running]> on host 3517d925e010
[2025-09-24T09:24:29.854+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='sales_dag' AIRFLOW_CTX_TASK_ID='final_merge.merge_data_to_mainTable' AIRFLOW_CTX_EXECUTION_DATE='2025-09-23T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-09-23T00:00:00+00:00'
[2025-09-24T09:24:29.856+0000] {sales_dag.py:190} INFO - Mergeing data from staging to main table has been started
[2025-09-24T09:24:29.908+0000] {base.py:73} INFO - Using connection ID '***_conn' for task execution.
[2025-09-24T09:24:29.964+0000] {sql.py:418} INFO - Running statement: 
    MERGE INTO sales.transactions AS T
    USING sales.transactions_staging AS S
    ON T.unique_row_id = S.unique_row_id
    WHEN MATCHED THEN 
        UPDATE SET 
            InvoiceNo = S.InvoiceNo,
            StockCode = S.StockCode,
            Description = S.Description,
            Quantity    = S.Quantity,
            InvoiceDate = S.InvoiceDate,
            UnitPrice   = S.UnitPrice,
            CustomerID  = S.CustomerID,
            Country     = S.Country       
    WHEN NOT MATCHED THEN
    INSERT(unique_row_id ,InvoiceNo ,StockCode ,Description ,Quantity ,InvoiceDate ,UnitPrice ,CustomerID ,Country)
    VALUES(S.unique_row_id ,S.InvoiceNo ,S.StockCode ,S.Description ,S.Quantity ,S.InvoiceDate ,S.UnitPrice ,S.CustomerID ,S.Country)
    , parameters: None
[2025-09-24T09:24:30.014+0000] {sql.py:427} INFO - Rows affected: 0
[2025-09-24T09:24:30.016+0000] {sales_dag.py:211} INFO - Mergeing data into main table done
[2025-09-24T09:24:30.016+0000] {python.py:194} INFO - Done. Returned value was: None
[2025-09-24T09:24:30.066+0000] {taskinstance.py:1398} INFO - Marking task as SUCCESS. dag_id=sales_dag, task_id=final_merge.merge_data_to_mainTable, execution_date=20250923T000000, start_date=20250924T092429, end_date=20250924T092430
[2025-09-24T09:24:30.144+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-09-24T09:24:30.201+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
